### ISSUE TITLE
Batocera ES fork support

### ISSUE THREAD

**Issue by Redemp** [losernator/es-theme-ssimple-ve#1]
Would it be possible to looking into supporting Batocera ES fork? 

https://batocera.org/
https://github.com/batocera-linux/batocera-emulationstation

https://discord.com/invite/JXhfRTr

Thanks!

**Comment by losernator** [comment]
Batocera ES seems to have some issue on <size> tag with video.
I just update the theme and tested on windows batocera ES. Should work on other platform.
